- hosts: c6steve
  become: true
  remote_user: root

  tasks:
  - name: ==> 2. Install apache & vsftp & net-snmp .
    yum: name={{ item }} state=present
    with_items:
      - httpd
      - vsftpd
      - net-snmp

  - name: ==> 3. set vsftp config
    template:
      src: "./templates/vsftpd.conf.j2"
      dest: "/etc/vsftpd/vsftpd.conf"

  - name: ==> 4. touch vsftp chroot_list
    file: path=/etc/vsftpd/chroot_list state=touch

  - name: ==> 5. set snmp config
    template:
      src: "./templates/snmpd.conf.j2"
      dest: "/etc/snmp/snmpd.conf"

  - name: ==> 6. set virtualhost config
    template:
      src: "./templates/httpd.conf.j2"
      dest: "/etc/httpd/conf/httpd.conf"

  - name: ==> 7. Running & enable Service .
    service: name={{ item }} state=started enabled=yes
    with_items:
      - httpd
      - vsftpd
      - snmpd

